# Generated by Django 4.0.5 on 2022-06-04 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0003_alter_image_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='comments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='photoapp.comment'),
        ),
        migrations.AlterField(
            model_name='image',
            name='likes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='photoapp.like'),
        ),
    ]
