# Generated by Django 4.0.5 on 2022-06-05 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0006_alter_profile_email_alter_profile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='password',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
