# Generated by Django 4.0.5 on 2022-06-05 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0007_remove_profile_email_remove_profile_fullname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='photoapp.profile'),
        ),
    ]
